version: "3.0"
services:
  devcontainer:
    build: ./devcontainer
    environment:
      - DEV_PASSWORD=${DEV_PASSWORD:-devtools}
      - SESSION_PLANTUML_SERVER_URL=http://plantuml-server:8080
      - SESSION_DOCKER_PUBLIC_ADDRESS=docker
      - SESSION_DOCKER_HOST=tcp://docker:2376
      - SESSION_DOCKER_TLS_VERIFY=1
      - SESSION_DOCKER_CERT_PATH=/etc/docker/certs/client
    ports:
      - "2222:22/tcp"   # sshd
      - "8443:443/tcp"  # code-server
      - "8080:8080/tcp" # mkdocs-serve
    volumes:
      - "local-data:/root"                  # developer data
      - "docker-certs:/etc/docker/certs:ro" # certs shared from docker:dind for docker TLS
  plantuml-server:
    image: plantuml/plantuml-server
  docker:
    image: docker:dind
    privileged: true
    volumes:
      - docker-certs:/certs    # certs shared with devcontainer for TLS
      - docker:/var/lib/docker # prevent docker:dind's VOLUME directive from spawning endless anon volumes by giving it a named volume instead
    ports:
      - "80:80/tcp"     # http
      - "443:443/tcp"   # https
      - "3222:2222/tcp" # nested sshd
      - "9443:8443/tcp" # nested code-server
volumes:
  docker:
  docker-certs:
  local-data:
