version: "3.0"
services:
  devcontainer:
    build: ./devcontainer
    environment:
      - CONNECTION_TOKEN=${DEVTOOLS_TOKEN:-devtools}
      - SESSION_PLANTUML_SERVER_URL=http://plantuml-server:8080
      - SESSION_DOCKER_PUBLIC_ADDRESS=docker
      - SESSION_DOCKER_HOST=tcp://docker:2376
      - SESSION_DOCKER_TLS_VERIFY=1
      - SESSION_DOCKER_CERT_PATH=/etc/docker/certs/client
    ports:
      - "222:22/tcp"                             # sshd
      - "${DEVTOOLS_PORT_INGRESS:-8443}:443/tcp" # https
    volumes:
      - "local-data:/root"
      - "docker-certs:/etc/docker/certs:ro"
    # on some linux systems, terminator cannot start /bin/bash because of a system call to fdwalk
    # that raises a seccomp issue similar to https://github.com/mviereck/x11docker/issues/346
    # this doesn't seem to happen on Docker Desktop (windows)
    security_opt:
      - seccomp:unconfined
  plantuml-server:
    image: plantuml/plantuml-server
  docker:
    image: docker:dind
    privileged: true
    volumes:
      - docker-certs:/certs
      - docker:/var/lib/docker
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "${DOCKER_EXTRA_PORTS:-5000-5010}:${DOCKER_EXTRA_PORTS:-5000-5010}/tcp"
volumes:
  docker:
  docker-certs:
  local-data:
