version: "3.2"
services:
  devcontainer:
    build: .
    environment:
      - CONNECTION_TOKEN=${DEVTOOLS_TOKEN:-devtools}
      - SESSION_PLANTUML_SERVER_URL=http://plantuml-server:8080
      - SESSION_DOCKER_PUBLIC_ADDRESS=docker
      - SESSION_DOCKER_HOST=tcp://docker:2376
      - SESSION_DOCKER_TLS_VERIFY=1
      - SESSION_DOCKER_CERT_PATH=/etc/docker/certs/client
    ports:
      # mkdocs-serve when running
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
      # sshd
      - target: 22
        published: 222
        protocol: tcp
        mode: host
      # vscode-server
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: local-data
        target: /root
      - type: volume
        source: docker-certs
        target: /etc/docker/certs
        read_only: true
  plantuml-server:
    image: plantuml/plantuml-server
  docker:
    image: docker:dind
    privileged: true
    volumes:
      - type: volume
        source: docker-certs
        target: /certs
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
volumes:
  local-data:
  docker-certs:
