version: "3.2"
services:
  devcontainer:
    build: .
    environment:
      - SESSION_PLANTUML_SERVER_URL=http://plantuml-server:8080
      - SESSION_DOCKER_PUBLIC_ADDRESS=docker
      - SESSION_DOCKER_HOST=tcp://docker:2376
      - SESSION_DOCKER_TLS_VERIFY=1
      - SESSION_DOCKER_CERT_PATH=/etc/docker/certs/client
      - ROOT_PASSWORD=${DEVTOOLS_PASSWORD:-devtools}
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
      - target: 22
        published: 222
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: local-data
        target: /root
      - type: volume
        source: docker-certs
        target: /etc/docker/certs
        read_only: true
    # on some linux systems, terminator cannot start /bin/bash because of a system call to fdwalk
    # that raises a seccomp issue similar to https://github.com/mviereck/x11docker/issues/346
    # this doesn't seem to happen on Docker Desktop (windows)
    security_opt:
      - seccomp:unconfined
  plantuml-server:
    image: plantuml/plantuml-server
  docker:
    image: docker:dind
    privileged: true
    volumes:
      - type: volume
        source: docker-certs
        target: /certs
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
volumes:
  local-data:
  docker-certs:
