#! /bin/sh
set -e

SOURCE_DIR=$(pwd)

echo "Installing"
dnf -q -y update

echo "Installing common tools"
dnf -q -y install \
    boxes         \
    cowsay        \
    figlet        \
    iputils       \
    lolcat        \
    which

echo "Installing SSH"
dnf -q -y install openssh-clients openssh-server
ssh-keygen -A
echo "PermitRootLogin yes" > /etc/ssh/sshd_config.d/devtools.conf

echo "Installing x11 utilities"
dnf -q -y install        \
    xclock               \
    xorg-x11-server-Xorg \
    xorg-x11-xauth       \
    xset

echo "Installing terminal emulator"
dnf -q -y install terminator

echo "Installing bash-completion"
dnf -q -y install bash-completion

echo "Installing git"
dnf -q -y install git
cat > /etc/profile.d/git-profile.sh <<EOF
GIT_PS1_SHOWDIRTYSTATE=1
. /usr/share/git-core/contrib/completion/git-prompt.sh
PS1='[sample-project \\W\$(__git_ps1 " (%s)")]\\$ '
EOF

echo "Installing docker"
dnf -q -y install 'dnf-command(config-manager)'
dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
dnf -q -y install docker-ce-cli docker-compose-plugin

echo "Installing python3 and mkdocs"
dnf -q -y install python3 python3-pip
pip3 install mkdocs
pip3 install plantuml-markdown

echo "Installing mkdocs to PDF"
dnf -q -y install pango
pip3 install weasyprint
pip3 install mkdocs-with-pdf

echo "Installing kubernetes utilities: kubectl"
curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
echo "source <(kubectl completion bash)" > /usr/share/bash-completion/completions/kubectl # yes, /usr/share instead of /usr/local/share

echo "Installing kubernetes utilities: kind"
curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.17.0/kind-linux-amd64
chmod +x ./kind
mv ./kind /usr/local/bin/kind
echo "source <(kind completion bash)" > /usr/share/bash-completion/completions/kind # yes, /usr/share instead of /usr/local/share

echo "Installing kubernetes utilities: helm"
curl -Lo ./helm.tar.gz https://get.helm.sh/helm-v3.10.2-linux-amd64.tar.gz
tar -zxvf helm.tar.gz
mv linux-amd64/helm /usr/local/bin/helm
rm -rf linux-amd64 helm.tar.gz
echo "source <(helm completion bash)" > /usr/share/bash-completion/completions/helm # yes, /usr/share instead of /usr/local/share

echo "Installing kubernetes utilities: k9s"
curl -Lo ./k9s.tar.gz https://github.com/derailed/k9s/releases/download/v0.27.3/k9s_linux_amd64.tar.gz
mkdir -p /usr/local/lib/k9s
tar -zxvf ./k9s.tar.gz -C /usr/local/lib/k9s
rm -f ./k9s.tar.gz
/bin/ln -s  /usr/local/lib/k9s/k9s /usr/local/bin/k9s

echo "Installing openvscode-server"
curl -Lo ./openvscode-server.tar.gz https://github.com/gitpod-io/openvscode-server/releases/download/openvscode-server-v1.76.0/openvscode-server-v1.76.0-linux-x64.tar.gz
mkdir -p /usr/local/lib/openvscode-server
tar -zxvf ./openvscode-server.tar.gz --strip-components=1 -C /usr/local/lib/openvscode-server
rm -f ./openvscode-server.tar.gz
/bin/ln -s /usr/local/lib/openvscode-server/bin/openvscode-server /usr/local/bin/openvscode-server

echo "Installing utilities on PATH"
ln -s $SOURCE_DIR/bin/* /usr/local/bin/

echo "Done installing"
