version: "3.2"
services:
  devcontainer:
    build: .
    command: pause
    environment:
      - PLANTUML_SERVER_URL=http://plantuml-server:8080 # no trailing slash
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: local-data
        target: /root
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
  plantuml-server:
    image: plantuml/plantuml-server
volumes:
  local-data:
