services:
  devcontainer:
    build: .
    command: pause
    hostname: devcontainer
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: local-data
        target: /root
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
  plantuml-server:
    image: plantuml/plantuml-server
volumes:
  local-data:
