services:
  devcontainer:
    build: .
    command: pause
    hostname: devcontainer
    container_name: devcontainer
    volumes:
      - type: volume
        source: local-data
        target: /root
volumes:
  local-data: