services:
  devcontainer:
    build: .
    command: pause
    hostname: devcontainer
    volumes:
      - type: volume
        source: local-data
        target: /root
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
volumes:
  local-data:
