#! /bin/sh
set -e

SOURCE_DIR=$(pwd)

echo "Installing"
dnf -q -y update

echo "Installing common tools"
dnf -q -y install which

echo "Installing git"
dnf -q -y install git
ln -s /usr/share/bash-completion/completions/git /etc/profile.d/git-completion.sh
cat > /etc/profile.d/git-profile.sh <<EOF
GIT_PS1_SHOWDIRTYSTATE=1
. /usr/share/git-core/contrib/completion/git-prompt.sh
PS1='[\\u@\\h \\W\$(__git_ps1 " (%s)")]\\$ '
EOF

echo "Installing x11 utilities"
dnf -q -y install           \
    xorg-x11-server-utils   \
    xorg-x11-server-Xorg    \
    xorg-x11-xauth

echo "Installing Docker"
dnf -q -y install 'dnf-command(config-manager)'
dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
dnf -q -y install docker-ce-cli docker-compose-plugin

echo "Installing python3 and mkdocs"
dnf -q -y install python39
pip3 install mkdocs

echo "Installing other utilities on PATH"
ln -s $SOURCE_DIR/bin/* /usr/local/bin/

echo "Installing entrypoint"
ln -s $SOURCE_DIR/entrypoint /usr/local/bin/entrypoint

echo "Done installing"
